/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import biblioteca.Administrador;
import biblioteca.Emprestimo;
import biblioteca.Livro;
import biblioteca.PerfilUsuario;
import biblioteca.SistemaBiblioteca;
import biblioteca.Usuario;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author ggois
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private PainelLogin painelLogin;
    private PainelDashboard painelDashboard;
    private PainelCadastroLivro painelCadastroLivro;
    private PainelGestaoUsuario painelGestaoUsuario;
    private Usuario usuarioLogado;
    
    private SistemaBiblioteca sistema;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        this.sistema = new SistemaBiblioteca();
        
        painelLogin = new PainelLogin(this);
        painelDashboard = new PainelDashboard(this);
        painelCadastroLivro = new PainelCadastroLivro(this);
        painelGestaoUsuario = new PainelGestaoUsuario(this);
        
        this.setContentPane(painelLogin);
    }
    
    public void setUsuarioLogado(Usuario usuario) {
        this.usuarioLogado = usuario;
    }
    
    public Usuario getUsuarioLogado() {
        return this.usuarioLogado;
    }
    
    public void trocarPainel(JPanel painel) {
        if (painel instanceof PainelDashboard) {
            ((PainelDashboard) painel).atualizarTabelaDeLivros();
            ((PainelDashboard) painel).atualizarTabelaEmprestimos();
        } else if (painel instanceof PainelGestaoUsuario) {
            ((PainelGestaoUsuario) painel).atualizarTabelaUsuarios();
        }
        
        this.setContentPane(painel);
        this.pack();
        this.revalidate();
        this.setLocationRelativeTo(null);
    }
    
    public PainelDashboard getPainelDashboard() {
        return painelDashboard;
    }

    public PainelCadastroLivro getPainelCadastroLivro() {
        return painelCadastroLivro;
    }

    public PainelGestaoUsuario getPainelGestaoUsuario() {
        return painelGestaoUsuario;
    }
    
    public PainelLogin getPainelLogin() {
        return painelLogin;
    }
    
    public SistemaBiblioteca getSistema() {
        return this.sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIblioteca Digital");
        setMaximumSize(new java.awt.Dimension(720, 720));
        setMinimumSize(new java.awt.Dimension(720, 720));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
